apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpcc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpcc-label 
  template:
    metadata:
      labels:
        app: tpcc-label
    spec:
      containers:
      - name: flask 
        image: quay.io/sacramento-20/playlists-recommender-system
        imagePullPolicy: Always
        ports:
        - containerPort: 32194
        volumeMounts:
        - name: share-volume
          mountPath: /model/
        env:
        - name: VERSION
          value: "v0.1"
      - name: train
        imagePullPolicy: Always
        image: quay.io/sacramento-20/playlists-model-recommender
        volumeMounts:
        - name: share-volume
          mountPath: /model/
        env:
        - name: URL_DATASET
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"

      volumes:
        - name: share-volume
          persistentVolumeClaim:
            claimName: tpcc-volume
