apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpcc-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tpcc-label 
  template:
    metadata:
      labels:
        app: tpcc-label
    spec:
      containers:
      - name: flask 
        image: quay.io/sacramento-20/playlists-recommender-system
        ports:
        - containerPort: 32194
      - name: train
        image: quay.io/sacramento-20/playlists-model-recommender
