apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  namespace: kaelaugusto 
  name: tpcc-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
